highlighter: rouge
permalink: none

# å¿½ç•¥æ–‡ä»¶
exclude: [LICENSE, local.sh, docker.sh, Rakefile, Gemfile, Gemfile.lock, README.md, vendor]

kramdown:
  input: GFM
  hard_wrap: false

plugins:

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/


title: ç­¾åä½ç½® #ç½‘é¡µä¿¡æ¯
url: https://blog.yourwebsite.com #CNAMEåœ°å€
author: æ¶¦å–‰ç³– #ä½œè€…


# ç¤¾äº¤é“¾æ¥
social:
  name: yourNickName #æ˜µç§°æˆ–åå­—
  wechat: https://github.io #å¾®ä¿¡äºŒç»´ç é“¾æ¥
  telegram: https://github.io #telegramé“¾æ¥

# é¡µè„šä¿¡æ¯
info-url:
  github: https://www.github.io #githubåœ°å€
  email: joebrack331@gmail.com #é‚®ç®±åœ°å€
# domain: https://github.com/baiyuNinja

# åŸºæœ¬å›ºå®šçš„é™æ€èµ„æºï¼Œå»ºè®®ä½¿ç”¨è‡ªå·±çš„UCloudé¦™æ¸¯åŒºå¯¹è±¡å­˜å‚¨
# æˆ–è€…ä½¿ç”¨æ ¹ç›®å½•ä¸‹çš„é™æ€æ–‡ä»¶
cdn-url:
  jquery-min: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Fjquery.min.js
  toc-js: /js/toc/toc.js
# toc-js: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Ftoc.js
  css: /css/style.css #css: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Fstyle.css
# é¦–é¡µlogo
  logo: https://1024bit.cn-bj.ufileos.com/blog%2Fimages%2Fcat%2Fcat.png
# ç½‘ç«™æ ‡ç­¾å›¾æ ‡
  fav: https://1024bit.cn-bj.ufileos.com/blog%2Fimages%2Fcat%2Ffav.png

# åšå®¢ä¸­å¯å®šåˆ¶çš„å­—ç¬¦ä¸²
string:
  first-year: 2020 YML
  home-name: NAME YML
  index: å…³äºäººç”Ÿ
# å¦‚éœ€å±•ç¤ºåœ¨çº¿ç®€å†ï¼Œè¯·å¡«å……åœ¨çº¿ç®€å†é“¾æ¥
  projects: å®ä¹  / é¡¹ç›® / <a href="/" target="_blank">æˆ‘çš„ç®€å†</a> YML
  blog: ğŸ” <a href="/blog/categories.html">åˆ†ç±»</a> YML
  about: å…³äºæˆ‘
  copyright: yourCopyright YML
